type Post @mongo(name: "posts") {
    user_id: String!
    title: String!
    description: String!
    tags: [Tag]
    user: User @link(field: "user_id")
}

type Tag {
    name: String!
}

type Query {
    posts: [Post]
}

type Mutation {
    addPost(user_id: String!, title: String!, description: String!): Post
}